{
 "title": "Mesh",
 "description": "ttt",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": " Meshtastic Ukraine ",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "<script src=\n\"https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js\">\n</script>\n<style>\n\n#qrcode {\n  border: 10px solid #73bf69;\n  background-color: #73bf69;\n}\n</style>\n<center>Join us now : <a href=\"https://t.me/meshtastic_ua\" target=\"_blank\">t.me/meshtastic_ua</a>\n<p></p>\n    <main>\n        <div id=\"qrcode\" onclick=\"openLink()\"></div>\n    </main>\n    \n</center>\n\n<script>\n    let url = \"https://meshtastic.org/e/#CjASIFziz2R01sx4MpCcWd6Z49dJjCXa_IJYG5bDRi1CL3dcGghMb25nRmFzdCgBMAESDggBOAJABUgBUAxYAWAB\";\n    function whenAvailable(name, callback) {\n            // Store the interval id\n        var intervalId = window.setInterval(function() {\n            if (window[name]) {\n                    // Clear the interval id\n                    window.clearInterval(intervalId);\n                // Call back\n                callback(window[name]);\n            }\n        }, 10);\n    };\n\n    whenAvailable(\"QRCode\", function(t) {\n        var qrcode = new QRCode(\"qrcode\", \n        {\n            text: url,\n            colorDark : \"#111217\", \n\t        colorLight : \"#73bf69\",\n        });\n        console.log('qr render');\n    });\n\n    function openLink() {\n        window.open(url, '_blank').focus();\n    };\n</script>\n\n    "
   }
  },
  {
   "type": "geomap",
   "gridPos": { "h": 14, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT concat('!', to_hex(did)) AS \"nodeId\", did, long_name AS \"Name\", hw_model AS \"HW\", rssi AS \"RSSI\", rxsnr AS \"rx snr\", lat, long, last_dt AS \"Last packet\", hoplimir AS \"Hop limit\", batlevel AS \"Bat level\" FROM users  WHERE $__timeFilter(last_dt)"
    }
   ]
  },
  {
   "title": "Users count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT COUNT(did) FROM users" }
   ]
  },
  {
   "title": "Users online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(did) FROM users WHERE $__timeFilter(last_dt)"
    }
   ]
  },
  {
   "title": "Chat",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT chat.dt, users.long_name, chat.text, concat('!', to_hex(chat.gateway_id)) AS Gateway, chat.gateway_id, users.did FROM chat LEFT OUTER JOIN users ON chat.did = users.did order by chat.dt DESC LIMIT 100 "
    }
   ]
  },
  {
   "title": "Users",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT long_name AS \"Name\", short_name AS \"Short\", hw_model AS \"HW model\", rssi AS \"RX RSSI\", rxsnr AS \"RX Snr\", hoplimir AS \"HopLimit\", last_dt AS \"Last\", did, concat('!', to_hex(gateway_id)) AS Gateway, gateway_id FROM users ORDER BY last_dt DESC "
    }
   ]
  },
  {
   "title": "Leaderboard By Observed Frames",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "query": "SELECT cumulative_sum(count(\"gateway_id\")) FROM \"raw\" WHERE $timeFilter  GROUP BY time(1m), \"gateway_id\""
    }
   ]
  }
 ]
}