{
 "title": "Mesh node",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "nodeId",
    "label": "Node Name",
    "query": "SELECT\n    concat(long_name, ' ', hw_model, ' !', to_hex(did))  AS \"__text\", did AS \"__value\"\nFROM\n  users"
   }
  ]
 },
 "panels": [
  {
   "title": "Last packet",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "raw",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idName::tag", "operator": "=~", "value": "/^$nodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Track",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 17, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "alias": "lat",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pos",
     "select": [
      [
       { "params": [ "latitude_i" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idName", "operator": "=~", "value": "/^$nodeId$/" }
     ]
    },
    {
     "alias": "lon",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pos",
     "select": [
      [
       { "params": [ "longitude_i" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idName", "operator": "=~", "value": "/^$nodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Last packet from gateway",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT users.long_name, users.did as Did FROM users AS u LEFT OUTER JOIN users ON u.gateway_id = users.did WHERE u.did = $nodeId"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Battery Level",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "info",
     "select": [
      [
       { "params": [ "battery_level" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idName", "operator": "=~", "value": "/^$nodeId$/" }
     ]
    },
    {
     "alias": "Channel use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "info",
     "select": [
      [
       { "params": [ "channel_utilization" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idName", "operator": "=~", "value": "/^$nodeId$/" }
     ]
    },
    {
     "alias": "Hops",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "raw",
     "select": [
      [
       { "params": [ "hopLimit" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idName", "operator": "=~", "value": "/^$nodeId$/" }
     ]
    },
    {
     "alias": "Rssi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "raw",
     "select": [
      [
       { "params": [ "rxRssi" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idName", "operator": "=~", "value": "/^$nodeId$/" }
     ]
    },
    {
     "alias": "SNR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "raw",
     "select": [
      [
       { "params": [ "rxSnr" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idName", "operator": "=~", "value": "/^$nodeId$/" }
     ]
    },
    {
     "alias": "Voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "info",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idName", "operator": "=~", "value": "/^$nodeId$/" }
     ]
    },
    {
     "alias": "AirUtilTX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "info",
     "select": [
      [
       { "params": [ "air_util_tx" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idName", "operator": "=~", "value": "/^$nodeId$/" }
     ]
    },
    {
     "alias": "Altitude",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pos",
     "select": [
      [
       { "params": [ "altitude" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idName", "operator": "=~", "value": "/^$nodeId$/" }
     ]
    },
    {
     "alias": "Msg/minute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "raw",
     "query": "SELECT count(\"id\")/15 FROM \"raw\" WHERE (\"gateway_id\"::tag =~ /^$nodeId$/ OR \"idName\"::tag =~ /^$nodeId$/) AND time > now() - 15m",
     "select": [
      [
       { "params": [ "hopLimit" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idName", "operator": "=~", "value": "/^$nodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pos",
     "select": [
      [
       { "params": [ "altitude" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idName", "operator": "=~", "value": "/^$nodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "alias": "voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "info",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idName", "operator": "=~", "value": "/^$nodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "SNR",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "alias": "snr",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "info",
     "select": [
      [
       { "params": [ "rx_snr" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idName", "operator": "=~", "value": "/^$nodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Rssi",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "alias": "rssi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "info",
     "select": [
      [
       { "params": [ "rx_rssi" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idName", "operator": "=~", "value": "/^$nodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "info",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idName", "operator": "=~", "value": "/^$nodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "info",
     "select": [
      [
       { "params": [ "relative_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idName", "operator": "=~", "value": "/^$nodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "info",
     "select": [
      [
       { "params": [ "barometric_pressure" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idName", "operator": "=~", "value": "/^$nodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Gas Res",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "mΩ" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "info",
     "select": [
      [
       { "params": [ "gas_resistance" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idName", "operator": "=~", "value": "/^$nodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Environment Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "info",
     "select": [
      [
       { "params": [ "env_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idName", "operator": "=~", "value": "/^$nodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Environment Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "info",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idName", "operator": "=~", "value": "/^$nodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Leaderboard By Observed Frames",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "query": "SELECT cumulative_sum(count(\"gateway_id\")) FROM \"raw\" WHERE (\"idName\" =~ /^$nodeId$/) AND $timeFilter  GROUP BY time(1m), \"gateway_id\""
    }
   ]
  },
  {
   "title": "Own messages",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "raw",
     "query": "SELECT last(\"payload\"), last(\"gateway_id\"), last(\"portnum\"), last(\"id\") FROM \"raw\" WHERE (\"idName\" =~ /^$nodeId$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "gateway_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "portnum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "payload" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "rxTime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 1000" ], "type": "math" }
      ],
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "hopLimit" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "priority" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "idName", "operator": "=~", "value": "/^$nodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Routed messages",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "raw",
     "query": "SELECT last(\"payload\"), last(\"gateway_id\"), last(\"portnum\"), last(\"id\") FROM \"raw\" WHERE (\"idName\" =~ /^$nodeId$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "fram" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "portnum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "payload" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "rxTime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 1000" ], "type": "math" }
      ],
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "hopLimit" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "priority" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "gateway_id::tag", "operator": "=~", "value": "/^$nodeId$/" },
      { "condition": "AND", "key": "idName::tag", "operator": "!~", "value": "/^$nodeId$/" }
     ]
    }
   ]
  }
 ]
}